<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>true</IsTestProject>
		<RootNamespace>UITests</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>$(DefineConstants);IOS</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Appium.WebDriver" Version="5.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="NUnit" Version="4.1.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
		<PackageReference Include="VisualTestUtils" Version="0.9.46-beta" />
		<PackageReference Include="VisualTestUtils.MagickNet" Version="0.9.46-beta" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\UITests.Shared\**\*.cs" LinkBase="Shared" Visible="false" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Syncfusion.UITestHelpers.Appium" Version="*" />
	  <PackageReference Include="Syncfusion.UITestHelpers.Core" Version="*" />
	  <PackageReference Include="Syncfusion.UITestHelpers.NUnit" Version="*" /> <PackageReference Include="Syncfusion.UITestHelpers.Screenshot" Version="*" />
	</ItemGroup>

</Project>