<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>SfButtonSample</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>SfButtonSample</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.SfButtonSample</ApplicationId>
		<ApplicationIdGuid>3338dcb4-92d9-41a3-95c7-d81e10d5b4a8</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<AndroidSigningKeyStore>key.keystore</AndroidSigningKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>kanna007</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>MauiAlias</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>kanna007</AndroidSigningKeyPass>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-maccatalyst|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>kanna007</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>MauiAlias</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>kanna007</AndroidSigningKeyPass>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-maccatalyst|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationTitle>SfButtonSample</ApplicationTitle>
	  <ApplicationId>com.companyname.SfButtonSample</ApplicationId>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <DefineConstants>TRACE;DEBUG;NET;NET8_0;NETCOREAPP;ENABLE_TEST_CLOUD;</DefineConstants>
	  <WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
		<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
	</PropertyGroup>
	
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />
		<MauiFont Include="Resources\Fonts\SegmentIcon.ttf" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Fonts\Roboto-Medium.ttf" />
	  <None Remove="Resources\Fonts\Roboto-Regular.ttf" />
	  <None Remove="Resources\Images\avatar1.png" />
	  <None Remove="Resources\Images\avatar10.png" />
	  <None Remove="Resources\Images\images.jpg" />
	  <None Remove="Resources\Images\nature.jpg" />
	  <None Remove="Resources\Images\nature1.jpg" />
	  <None Remove="Resources\Images\user.jpg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Buttons" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="*" />
		<PackageReference Include="Syncfusion.Maui.DataSource" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Expander" Version="*" />
		<PackageReference Include="Syncfusion.Maui.GridCommon" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Inputs" Version="*" />
		<PackageReference Include="Syncfusion.Maui.ListView" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Popup" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Sliders" Version="*" />
		<PackageReference Include="Syncfusion.Maui.TabView" Version="*" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="*" />
		
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="BugTesting\ButtonRtl1.xaml.cs">
	    <DependentUpon>ButtonRtl1.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="BugTesting\ButtonRtl2.xaml.cs">
	    <DependentUpon>ButtonRtl2.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Features\IsBusyFeature.xaml.cs">
	    <DependentUpon>IsBusyFeature.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

<ItemGroup>
		  <MauiXaml Update="BugTesting\Bug855758.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\Bug855758_1.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\Bug856303.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\Bug866382.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\ButtonRtl1.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\ButtonRtl2.xaml">
		    <Generator>MSBuild:Compile</Generator>
		  </MauiXaml>
		  <MauiXaml Update="BugTesting\SfButton1.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="BugTesting\SfButton2.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="BugTesting\SfButton3.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="BugTesting\XAMARIN_24037.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="BugTesting\XAMARIN_26477.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\ButtonInitial.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\ButtonSize.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\CommandSample.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\IsBusyFeature.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Layouts.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Properties.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Visualstate.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="SBSample\CustomizationDesktop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="SBSample\CustomizationMobile.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="SBSample\GettingStartedDesktop.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="SBSample\GettingStartedMobile.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\DynamicChange.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
  <PackageReference Include="Xamarin.TestCloud.Agent" Version="0.23.2" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-maccatalyst'">
  <PackageReference Include="Xamarin.TestCloud.Agent" Version="0.23.2" />
</ItemGroup>
</Project>
